### ISSUE TITLE
I cannot compile FortranParser using Cmake

### ISSUE THREAD

**Issue by s1291** [jacopo-chevallard/FortranParser#1]
Trying to build FortranParser but the process fails, here is what I do get when invoking Cmake:
Cmake .. -DCMAKE_INSTALL_PREFIX=../bin

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 5.4.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Adding default compiler flags for GNU compiler
-- Configuring rpath variables...
**_CMake Error: File /pkg-config.pc.cmake does not exist.
CMake Error at CMakeLists.txt:73 (configure_file):
  configure_file Problem configuring file

CMake Error: File /cmake_uninstall.cmake.in does not exist.
CMake Error at CMakeLists.txt:98 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!
See also "/home/samir/FortranParser/build/CMakeFiles/CMakeOutput.log"_**

I tried To compile it manually using:
`gfortran -c FortranParser_parameters.f90 FortranParser.f90`
`ar rcs libFortranParser.a FortranParser_parameters.o FortranParser.o`

and it compiles fine!!

**Comment by jacopo-chevallard** [comment]
Perhaps CMake is an overkill for such a simple project, but I'll take a look (or I'll change the instructions on the README)!
