### ISSUE TITLE
Does the code leak memory?

### ISSUE THREAD

**Issue by hennink** [jacopo-chevallard/FortranParser#3]
Thank you ever so much for sharing this code!

I just have one big concern:

Are you sure that the code doesn't leak memory? The [finalize](https://github.com/jacopo-chevallard/FortranParser/blob/07327af3940185766ecd2f429d00c2f3ccc063d7/src/FortranParser.f90#L151) procedure looks buggy to me. Shouldn't those `nullify` statements be `deallocate` statements? There's no point in nullifying a pointer just before it goes out of scope. If `ptr` is a pointer, then `deallocate(ptr)` does two things: (i) free the target (which must be something that can be deallocated), and (ii) nullify the pointer.

I also have two small remarks:

1. Aren't [the first lines in the constructor](https://github.com/jacopo-chevallard/FortranParser/blob/07327af3940185766ecd2f429d00c2f3ccc063d7/src/FortranParser.f90#L130) redundant? All non-character components are already properly initialized in the type declaration. (They either point to `null()` or are set to `0`.)

2. Though it's probably not a problem now, you could consider deferred-length allocatable characters to avoid having to use `MAX_FUN_LENGTH`.

**Comment by jacopo-chevallard** [comment]
> Are you sure that the code doesn't leak memory? The finalize procedure looks buggy to me. Shouldn't those nullify statements be deallocate statements? There's no point in nullifying a pointer just before it goes out of scope. If ptr is a pointer, then deallocate(ptr) does two things: (i) free the target (or produce an error if ptr doesn't point to an allocatable or pointer), and (ii) nullify the pointer.

I don't know, I think it's worth testing if indeed there is any memory leak, in which case feel free to open a pull request with the change you suggest! :) 

> Aren't the first lines in the constructor redundant? All non-character components are already properly initialized in the type declaration. (They either point to null() or are set to 0.)

They are redundant when you firstly use the type, but I'm not sure what happens if you want to re-initialize the class, in this case it may be useful to have those lines in the constructor, or maybe not?

> Though it's probably not a problem now, you could consider deferred-length allocatable characters to avoid having to use MAX_FUN_LENGTH

Yes indeed, now deferred-length allocatable characters are well enough supported (for instance from GCC) to allow us to use them in this class!

**Comment by hennink** [comment]
I had a look and these are my conclusions:

### The problem:
1. As it is, the type is indeed leaky. Just repeat one of the tests in a big loop, and you'll see the memory footprint grow indefinitely.

2. The solution I proposed above (replace `nullify(X)` by `deallocate(X)`) introduces a subtle bug in the constructor.
It think this is what Fortran does when it executes `eq_parser = EquationParser(FuncStr,Var)` (at least conceptually):
    a. Build `EquationParser(FuncStr,Var)` and store this is in `temp`.
    b. Copy `temp` to `eq_parser`. This means: copy the pointer components (i.e., a 'shallow' copy). Now the pointer components of `eq_parser` and `temp` have the same targets.
    c. Finalize `temp`, which deallocates the targets of the pointer components, thus leaving the pointer components of `eq_parser` dangling.

### The solution:
I can think of only one clear-cut solution:
1. replace `nullify(X)` by `deallocate(X)` in `finalize`, and

2. Replace `constructor` by a similar type-bound subroutine that is named `from_string` or something. I like this a lot better anyway.

### Can you help me?
If you agree with the proposed solution, I suggest the following division of labor:

- I will make the adjustments in the `FortranParser` module and the tests, push these, and make a pull request.

- You will adjust the documentation.

Is that agreeable to you?

**Comment by hennink** [comment]
I just thought of something else that *might* work with the interface as you created it, though I don't like it. You can overload the assignment operator. Add a method:
```
generic, public :: assignment(=) => deepcopy_EqParser
procedure, private :: deepcopy_EqParser
```
with implementation
```
subroutine deepcopy_EqParser(this,other)
    class(EquationParser), intent(out) :: this
    class(EquationParser), intent(in) :: other
    
    ! Allocate copies for all pointer components:
    allocate(this%ByteCode,source=other%ByteCode)
    ...
    
    ! Copy all non-pointer components:
    this%ByteCodeSize = other%ByteCodeSize
    ...
end subroutine deepcopy_EqParser
```
You would still need to change `finalize`.
